build:
  image: onaio/android:opensrp-client
  commands:
    - id
    - java -version
    - gradle --version
    - gradle clean --stacktrace
    - gradle opensrp-path:jacocoTestReport --info
    - cd opensrp-path
    - mvn org.eluder.coveralls:coveralls-maven-plugin:report -DrepoToken=${COVERALLS_REPO_TOKEN} -X
notify:
  email:
    from: $$FROM
    host: $$SMTP_HOST
    port: $$SMTP_PORT
    username: $$SMTP_USERNAME
    password: $$SMTP_PASSWORD
    recipients:
      - tech+drone@ona.io
    on_success: true
    on_failure: true

  slack:
    secrets: 'fAiZ4yA7DM6nUKh7nqsCTqZBb03VEAvi5NcRu5mNh5coNn/50XNeZl+qpv7Dw70Ef85Y/k68uc6KwTGVqPXEmVq9Hk3e7lqpBNN8rufvgCYDDGPmywBmU5BhSeykKo0Ee7llM3mRR/EipjIWw1+YvMcS3hCoygf/UlMDDhG0Jo0='
    username: 'drone'
    channel: '#opensrp-client'
    on_started: false
    on_success: true
    on_failure: true